### ISSUE TITLE
Sortie de Makefile surchargée

### ISSUE THREAD

**Issue by Toreben** [Tuteurs101/04-ft_ls-30-04-2019#1]
**Fichier :** Makefile

**Code source :**
```
Makefile:112: sources/*.d: No such file or directory
```
**Proposition :**
Alleger la sortie du Makefile pour le rendre plus friendly pour les nouveaux collaborateurs, et re-organiser les fichiers crees (ne pas avoir les .o et .d avec les .c)

**Details (optionnel) :**
Informations supplémentaires. (Points intéressants, notion etc.)

**Comment by Tuteurs101** [comment]
Affichage trop verbeux des fichiers. Faire un affichage pour indiquer que la compile a fonctionner. 
Tout cacher n'est pas forcément intéressant.

option make -k pour continuer la compilation + -s pour mode silencieux
