### ISSUE TITLE
Good comments ! (be careful with typo)

### ISSUE THREAD

**Issue by Cerveaulent** [Tuteurs101/04-ft_ls-30-04-2019#3]
**Fichier :** 
sort_algorithm.c
**Code source :**
```
/*
** insert_sort:
**
** Sorting a chained list of t_file according to a file_cmp function.
**
** Algorithm:
** Create a new chained list who will be entirely sorted from the beginning.
** Parse the old chained list from the first element, and insert each the
** element at the right place according to the funciton result.
*/

void			insert_sort(t_file **folder, t_file_cmp cmp_function)
{
...
}
```
**Proposition :**
```

```

**Details (optionnel) :**
Informations supplémentaires. (Points intéressants, notion etc.)
Juste pour dire que les commentaire pour expliquer un algo, quand on travaille en groupe c'est vachement bien !

**Comment by Tuteurs101** [comment]
Pensez à normaliser les commentaires pour qu'ils soient cohérents.

Les commentaires permettent de se retrouver ou aider les autres à comprendre le code.
Un code non commenté peut etre très dommageable pour d'autres, les choses deviennent facilement incompréhensible
