### ISSUE TITLE
Dependences

### ISSUE THREAD

**Issue by Cerveaulent** [Tuteurs101/04-ft_ls-30-04-2019#5]
**Fichier :** 
Makefile
**Code source :**
```
OBJS = $(addprefix $(SRCS_DIR),$(SRCS:.c=.o))
DEPENDENCIES = $(OBJS:.o=.d)

(...)

%.d:%.c
		$(CC) -MM $(addprefix -I , $(INCLUDES)) $(filter %.c, $^) > $@
		PREREQUISITES=$$(cat $@ | cut -d : -f 2) && \
			echo "$(@:%.d=%.o) $@:$$PREREQUISITES" > $@
```
**Proposition :**
```
(No propositions)
```

**Details (optionnel) :**
Informations supplémentaires. (Points intéressants, notion etc.)
La création de fichier *.d* pour compiler uniquement les fichier qui ont besoin de l'être est un ajout intéressant, d'autant plus quand le projet mets du temps à compiler

**Comment by Tuteurs101** [comment]
Permet d'éviter la compilation intégrale du projet a chaque modif (de header en l'occurence). Permet d'améliorer notre connaissance du makefile au fur et à mesure

--> Voir génération de Makefile automatique
