### ISSUE TITLE
Sortie si fail de malloc

### ISSUE THREAD

**Issue by Toreben** [Tuteurs101/04-ft_ls-30-04-2019#6]
**Fichier :** date_format.c

**Code source :**
```
str_date = ft_strdup(ctime(&date));
```

**Proposition :**
```
Si l'allocation foire, le programme n'affiche rien. Une gestion plus propre serait d'afficher le résultat tout de même, mais sans l'option défaillante
```

**Details (optionnel) :**

**Comment by Tuteurs101** [comment]
Les erreurs doivent etre anticipiées, et l'on doit choisir un comportement qui nous parait cohérent.
