### ISSUE TITLE
Utilisation de ternaire abusive

### ISSUE THREAD

**Issue by Toreben** [Tuteurs101/04-ft_ls-30-04-2019#7]
**Fichier :** ls_parsing

**Code source :**
```
error *= ((*files_names)[index++] = ft_strdup(*argv++)) == NULL ? 0 : 1;
```
**Proposition :**
```
Le ternaire peut etre evité en multipliant le error par le résultat de la comparaison directement :
error *= (((*files_names)[index++] = ft_strdup(*argv++)) != NULL);
```

**Details (optionnel) :**
Informations supplémentaires. (Points intéressants, notion etc.)

**Comment by Tuteurs101** [comment]
Utiliser les valeurs retournées par les condition (1 ou 0) pour ses opérations.
